# Generated by Django 4.1.7 on 2023-03-28 17:21

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bosses',
            fields=[
                ('Boss_id', models.AutoField(primary_key=True, serialize=False)),
                ('Boss_name', models.TextField(verbose_name='ПІБ')),
                ('Department', models.TextField(verbose_name='Підрозділ')),
                ('Boss_level', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)])),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.TextField(verbose_name='ПІБ')),
                ('position', models.TextField(verbose_name='Посада')),
                ('Employment_date', models.DateField(default=datetime.date(2023, 3, 28))),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('Boss', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.bosses')),
            ],
        ),
    ]
